# Generated by Django 4.0.4 on 2022-05-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('qid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_effective', models.DateTimeField()),
                ('date_previous_canceled', models.DateField(null=True)),
                ('is_owned', models.BooleanField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.address')),
            ],
        ),
    ]
